// <auto-generated />
using System;
using HealthIsWealth.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HealthIsWealth.Migrations
{
    [DbContext(typeof(HealthIsWealthContext))]
    [Migration("20260116152739_ProfilePictureSeed")]
    partial class ProfilePictureSeed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HealthIsWealth.Data.HealthIsWealthUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("ProfilePictureUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "3781efa7-66dc-47f0-860f-e506d04102e4",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "6eefe038-640c-46ef-8dc2-501dd2587bcc",
                            Email = "test1@gmail.com",
                            EmailConfirmed = true,
                            FirstName = "test",
                            LastName = "1",
                            LockoutEnabled = false,
                            NormalizedEmail = "TEST1@GMAIL.COM",
                            NormalizedUserName = "TEST1@GMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEFpodF1cGvp6qR+sGHALs38lEOHTzRTwLrz5i9gx0wPvc7EyR3TziR12wpHzTLg7Ew==",
                            PhoneNumberConfirmed = false,
                            ProfilePictureUrl = "/images/ProfilePicture/backgroundImage.jpg",
                            SecurityStamp = "5d3b3537-985e-4cdc-b631-057d8f8c3f71",
                            TwoFactorEnabled = false,
                            UserName = "test1@gmail.com"
                        },
                        new
                        {
                            Id = "6d3d2829-89fa-4095-b0f9-0ef8e802fd69",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "b61546de-7d78-4721-8167-34f33e4eb6f1",
                            Email = "test2@gmail.com",
                            EmailConfirmed = true,
                            FirstName = "test",
                            LastName = "2",
                            LockoutEnabled = false,
                            NormalizedEmail = "TEST2@GMAIL.COM",
                            NormalizedUserName = "TEST2@GMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEHq8wcDjmBmErbkuwwM4g352QPe9Oy+GLH4jpC/BqysnDSLr1dbHdORf3qYB7yrVUg==",
                            PhoneNumberConfirmed = false,
                            ProfilePictureUrl = "/images/ProfilePicture/Dog Icon.jpeg",
                            SecurityStamp = "a9d53481-342a-4d3a-aa91-165b38ba0a42",
                            TwoFactorEnabled = false,
                            UserName = "test2@gmail.com"
                        });
                });

            modelBuilder.Entity("HealthIsWealth.Domain.Booking", b =>
                {
                    b.Property<int>("BookingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BookingId"));

                    b.Property<int>("TimeslotId")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("BookingId");

                    b.HasIndex("TimeslotId");

                    b.HasIndex("UserId");

                    b.ToTable("Booking");

                    b.HasData(
                        new
                        {
                            BookingId = 1,
                            TimeslotId = 1,
                            UserId = "6d3d2829-89fa-4095-b0f9-0ef8e802fd69"
                        },
                        new
                        {
                            BookingId = 2,
                            TimeslotId = 2,
                            UserId = "6d3d2829-89fa-4095-b0f9-0ef8e802fd69"
                        },
                        new
                        {
                            BookingId = 3,
                            TimeslotId = 3,
                            UserId = "3781efa7-66dc-47f0-860f-e506d04102e4"
                        });
                });

            modelBuilder.Entity("HealthIsWealth.Domain.Facility", b =>
                {
                    b.Property<int>("FacilityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FacilityId"));

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Price")
                        .HasColumnType("real");

                    b.Property<string>("ThumbnailImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("VenueId")
                        .HasColumnType("int");

                    b.HasKey("FacilityId");

                    b.HasIndex("VenueId");

                    b.ToTable("Facility");

                    b.HasData(
                        new
                        {
                            FacilityId = 1,
                            Location = "01-01",
                            Name = "The Gym 1",
                            Price = 5f,
                            ThumbnailImageUrl = "images/facilities/one_gym_0.jpg",
                            VenueId = 1
                        },
                        new
                        {
                            FacilityId = 2,
                            Location = "01-02",
                            Name = "The Gym 2",
                            Price = 5f,
                            ThumbnailImageUrl = "images/facilities/one_gym_0.jpg",
                            VenueId = 1
                        },
                        new
                        {
                            FacilityId = 3,
                            Location = "02-01",
                            Name = "The Gym Premium",
                            Price = 10f,
                            ThumbnailImageUrl = "images/facilities/one_gym_0.jpg",
                            VenueId = 1
                        },
                        new
                        {
                            FacilityId = 4,
                            Location = "Level 2 MPH",
                            Name = "Court 1",
                            Price = 4f,
                            ThumbnailImageUrl = "images/facilities/court_complex_0.jpg",
                            VenueId = 2
                        },
                        new
                        {
                            FacilityId = 5,
                            Location = "Level 2 MPH",
                            Name = "Court 2",
                            Price = 4f,
                            ThumbnailImageUrl = "images/facilities/court_complex_0.jpg",
                            VenueId = 2
                        },
                        new
                        {
                            FacilityId = 6,
                            Location = "Level 2 MPH",
                            Name = "Basketball Court",
                            Price = 6f,
                            ThumbnailImageUrl = "images/facilities/court_complex_bb_court.jpg",
                            VenueId = 2
                        },
                        new
                        {
                            FacilityId = 7,
                            Location = "",
                            Name = "Private Pool",
                            Price = 8f,
                            ThumbnailImageUrl = "images/facilities/pool_space_0.jpg",
                            VenueId = 3
                        },
                        new
                        {
                            FacilityId = 8,
                            Location = "Level 3 MPH",
                            Name = "Court 1",
                            Price = 5f,
                            ThumbnailImageUrl = "images/facilities/universe_sports_court.jpg",
                            VenueId = 4
                        },
                        new
                        {
                            FacilityId = 9,
                            Location = "Level 3 MPH",
                            Name = "Court 2",
                            Price = 5f,
                            ThumbnailImageUrl = "images/facilities/universe_sports_court.jpg",
                            VenueId = 4
                        },
                        new
                        {
                            FacilityId = 10,
                            Location = "Level 3 MPH",
                            Name = "Court 3",
                            Price = 5f,
                            ThumbnailImageUrl = "images/facilities/universe_sports_court.jpg",
                            VenueId = 4
                        },
                        new
                        {
                            FacilityId = 11,
                            Location = "Level 2 MPH",
                            Name = "Basketball Court 1",
                            Price = 8f,
                            ThumbnailImageUrl = "images/facilities/universe_sports_bb_court.jpg",
                            VenueId = 4
                        },
                        new
                        {
                            FacilityId = 12,
                            Location = "Level 2 MPH",
                            Name = "Basketball Court 2",
                            Price = 8f,
                            ThumbnailImageUrl = "images/facilities/universe_sports_bb_court.jpg",
                            VenueId = 4
                        },
                        new
                        {
                            FacilityId = 13,
                            Location = "Ruby Wing 01-01",
                            Name = "Basketball Court 1",
                            Price = 8f,
                            ThumbnailImageUrl = "images/facilities/diamond_hub_bb_court.jpg",
                            VenueId = 5
                        },
                        new
                        {
                            FacilityId = 14,
                            Location = "Ruby Wing 01-02",
                            Name = "Basketball Court 2",
                            Price = 8f,
                            ThumbnailImageUrl = "images/facilities/diamond_hub_bb_court.jpg",
                            VenueId = 5
                        },
                        new
                        {
                            FacilityId = 15,
                            Location = "Sapphire Wing 01-01",
                            Name = "Luxury Pool 1",
                            Price = 32f,
                            ThumbnailImageUrl = "images/facilities/diamond_hub_pool.jpg",
                            VenueId = 5
                        },
                        new
                        {
                            FacilityId = 16,
                            Location = "Sapphire Wing 01-01",
                            Name = "Luxury Pool 2",
                            Price = 32f,
                            ThumbnailImageUrl = "images/facilities/diamond_hub_pool.jpg",
                            VenueId = 5
                        },
                        new
                        {
                            FacilityId = 17,
                            Location = "Emerald Wing 01-01",
                            Name = "Badminton Court 1",
                            Price = 10f,
                            ThumbnailImageUrl = "images/facilities/diamond_hub_court.jpg",
                            VenueId = 5
                        },
                        new
                        {
                            FacilityId = 18,
                            Location = "Emerald Wing 01-01",
                            Name = "Badminton Court 2",
                            Price = 10f,
                            ThumbnailImageUrl = "images/facilities/diamond_hub_court.jpg",
                            VenueId = 5
                        },
                        new
                        {
                            FacilityId = 19,
                            Location = "Gold Wing 01-01",
                            Name = "Luxury Private Gym",
                            Price = 20f,
                            ThumbnailImageUrl = "images/facilities/diamond_hub_gym.jpg",
                            VenueId = 5
                        });
                });

            modelBuilder.Entity("HealthIsWealth.Domain.FacilityImage", b =>
                {
                    b.Property<int>("FacilityImageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FacilityImageId"));

                    b.Property<int>("FacilityId")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("FacilityImageId");

                    b.HasIndex("FacilityId");

                    b.ToTable("FacilityImage");

                    b.HasData(
                        new
                        {
                            FacilityImageId = 1,
                            FacilityId = 19,
                            ImageUrl = "images/facilities/diamond_hub_gym_1.jpg"
                        },
                        new
                        {
                            FacilityImageId = 2,
                            FacilityId = 19,
                            ImageUrl = "images/facilities/diamond_hub_gym_2.jpg"
                        },
                        new
                        {
                            FacilityImageId = 3,
                            FacilityId = 3,
                            ImageUrl = "images/facilities/one_gym_1.jpg"
                        });
                });

            modelBuilder.Entity("HealthIsWealth.Domain.FacilitySport", b =>
                {
                    b.Property<int>("FacilitySportId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FacilitySportId"));

                    b.Property<int>("FacilityId")
                        .HasColumnType("int");

                    b.Property<int>("SportId")
                        .HasColumnType("int");

                    b.HasKey("FacilitySportId");

                    b.HasIndex("FacilityId");

                    b.HasIndex("SportId");

                    b.ToTable("FacilitySport");

                    b.HasData(
                        new
                        {
                            FacilitySportId = 1,
                            FacilityId = 6,
                            SportId = 1
                        },
                        new
                        {
                            FacilitySportId = 2,
                            FacilityId = 11,
                            SportId = 1
                        },
                        new
                        {
                            FacilitySportId = 3,
                            FacilityId = 12,
                            SportId = 1
                        },
                        new
                        {
                            FacilitySportId = 4,
                            FacilityId = 13,
                            SportId = 1
                        },
                        new
                        {
                            FacilitySportId = 5,
                            FacilityId = 14,
                            SportId = 1
                        },
                        new
                        {
                            FacilitySportId = 6,
                            FacilityId = 4,
                            SportId = 2
                        },
                        new
                        {
                            FacilitySportId = 7,
                            FacilityId = 5,
                            SportId = 2
                        },
                        new
                        {
                            FacilitySportId = 8,
                            FacilityId = 8,
                            SportId = 2
                        },
                        new
                        {
                            FacilitySportId = 9,
                            FacilityId = 9,
                            SportId = 2
                        },
                        new
                        {
                            FacilitySportId = 10,
                            FacilityId = 10,
                            SportId = 2
                        },
                        new
                        {
                            FacilitySportId = 11,
                            FacilityId = 17,
                            SportId = 2
                        },
                        new
                        {
                            FacilitySportId = 12,
                            FacilityId = 18,
                            SportId = 2
                        },
                        new
                        {
                            FacilitySportId = 13,
                            FacilityId = 4,
                            SportId = 3
                        },
                        new
                        {
                            FacilitySportId = 14,
                            FacilityId = 5,
                            SportId = 3
                        },
                        new
                        {
                            FacilitySportId = 15,
                            FacilityId = 8,
                            SportId = 3
                        },
                        new
                        {
                            FacilitySportId = 16,
                            FacilityId = 9,
                            SportId = 3
                        },
                        new
                        {
                            FacilitySportId = 17,
                            FacilityId = 10,
                            SportId = 3
                        },
                        new
                        {
                            FacilitySportId = 18,
                            FacilityId = 7,
                            SportId = 4
                        },
                        new
                        {
                            FacilitySportId = 19,
                            FacilityId = 15,
                            SportId = 4
                        },
                        new
                        {
                            FacilitySportId = 20,
                            FacilityId = 16,
                            SportId = 4
                        },
                        new
                        {
                            FacilitySportId = 21,
                            FacilityId = 1,
                            SportId = 5
                        },
                        new
                        {
                            FacilitySportId = 22,
                            FacilityId = 2,
                            SportId = 5
                        },
                        new
                        {
                            FacilitySportId = 23,
                            FacilityId = 3,
                            SportId = 5
                        },
                        new
                        {
                            FacilitySportId = 24,
                            FacilityId = 19,
                            SportId = 5
                        });
                });

            modelBuilder.Entity("HealthIsWealth.Domain.Review", b =>
                {
                    b.Property<int>("ReviewId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReviewId"));

                    b.Property<int>("BookingId")
                        .HasColumnType("int");

                    b.Property<string>("Feedback")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Rating")
                        .HasColumnType("real");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("ReviewId");

                    b.HasIndex("BookingId");

                    b.HasIndex("UserId");

                    b.ToTable("Review");

                    b.HasData(
                        new
                        {
                            ReviewId = 1,
                            BookingId = 1,
                            Feedback = "Dirty equipments but gym has alot of machines",
                            Rating = 3.5f,
                            UserId = "6d3d2829-89fa-4095-b0f9-0ef8e802fd69"
                        },
                        new
                        {
                            ReviewId = 2,
                            BookingId = 2,
                            Feedback = "Good location",
                            Rating = 4f,
                            UserId = "6d3d2829-89fa-4095-b0f9-0ef8e802fd69"
                        },
                        new
                        {
                            ReviewId = 3,
                            BookingId = 3,
                            Feedback = "Amazing pool",
                            Rating = 5f,
                            UserId = "3781efa7-66dc-47f0-860f-e506d04102e4"
                        });
                });

            modelBuilder.Entity("HealthIsWealth.Domain.Sport", b =>
                {
                    b.Property<int>("SportId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SportId"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ThumbnailImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SportId");

                    b.ToTable("Sport");

                    b.HasData(
                        new
                        {
                            SportId = 1,
                            Description = "A fun sport, enjoyable by many and with many formats. For your next game, book a court today.",
                            Name = "Basketball",
                            ThumbnailImageUrl = "images/sports/basketball.jpg"
                        },
                        new
                        {
                            SportId = 2,
                            Description = "An exciting racquet sport, enjoyable by all. Get your game on and book a court today.",
                            Name = "Badminton",
                            ThumbnailImageUrl = "images/sports/badminton.jpg"
                        },
                        new
                        {
                            SportId = 3,
                            Description = "An enjoyable racquet sport with strategy and skill. Play with a friend and book a court today.",
                            Name = "Tennis",
                            ThumbnailImageUrl = "images/sports/tennis.jpg"
                        },
                        new
                        {
                            SportId = 4,
                            Description = "A great sport for both fun and exercise. Cool down in the warm weather and book a pool today.",
                            Name = "Swimming",
                            ThumbnailImageUrl = "images/sports/swimming.jpg"
                        },
                        new
                        {
                            SportId = 5,
                            Description = "A gym is a good place to concentrate and workout. Find a space to train with us today.",
                            Name = "Gym",
                            ThumbnailImageUrl = "images/sports/gym.jpg"
                        });
                });

            modelBuilder.Entity("HealthIsWealth.Domain.Timeslot", b =>
                {
                    b.Property<int>("TimeslotId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TimeslotId"));

                    b.Property<DateTime>("EndDT")
                        .HasColumnType("datetime2");

                    b.Property<int>("FacilityId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDT")
                        .HasColumnType("datetime2");

                    b.HasKey("TimeslotId");

                    b.HasIndex("FacilityId");

                    b.ToTable("Timeslot");

                    b.HasData(
                        new
                        {
                            TimeslotId = 1,
                            EndDT = new DateTime(2026, 1, 14, 15, 0, 0, 0, DateTimeKind.Unspecified),
                            FacilityId = 1,
                            StartDT = new DateTime(2026, 1, 14, 13, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TimeslotId = 2,
                            EndDT = new DateTime(2024, 7, 1, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            FacilityId = 2,
                            StartDT = new DateTime(2024, 7, 1, 10, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TimeslotId = 3,
                            EndDT = new DateTime(2024, 7, 1, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            FacilityId = 2,
                            StartDT = new DateTime(2024, 7, 1, 11, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("HealthIsWealth.Domain.Venue", b =>
                {
                    b.Property<int>("VenueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VenueId"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PostalCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ThumbnailImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UnitNumber")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("VenueId");

                    b.ToTable("Venue");

                    b.HasData(
                        new
                        {
                            VenueId = 1,
                            Address = "211 Jurong East Street 21, Block 211, Singapore",
                            Name = "One Gym",
                            PostalCode = "600021",
                            ThumbnailImageUrl = "images/venues/one_gym_0.jpg",
                            UnitNumber = "#21-234"
                        },
                        new
                        {
                            VenueId = 2,
                            Address = "57 Lor. 5 Toa Payoh, Block 57",
                            Name = "Court Complex",
                            PostalCode = "310057",
                            ThumbnailImageUrl = "images/venues/court_complex_0.jpg",
                            UnitNumber = "#57-575"
                        },
                        new
                        {
                            VenueId = 3,
                            Address = "200 Commonwealth Ave W",
                            Name = "Pool Space",
                            PostalCode = "138677",
                            ThumbnailImageUrl = "images/venues/pool_space_0.jpg",
                            UnitNumber = "32"
                        },
                        new
                        {
                            VenueId = 4,
                            Address = "33 Yio Chu Kang Rd",
                            Name = "Universe Sports",
                            PostalCode = "545677",
                            ThumbnailImageUrl = "images/venues/universe_sports_0.jpg",
                            UnitNumber = ""
                        },
                        new
                        {
                            VenueId = 5,
                            Address = "1 Choa Chu Kang Street 53",
                            Name = "Diamond Hub",
                            PostalCode = "689236",
                            ThumbnailImageUrl = "images/venues/diamond_hub_0.jpg",
                            UnitNumber = ""
                        });
                });

            modelBuilder.Entity("HealthIsWealth.Domain.VenueImage", b =>
                {
                    b.Property<int>("VenueImageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VenueImageId"));

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("VenueId")
                        .HasColumnType("int");

                    b.HasKey("VenueImageId");

                    b.HasIndex("VenueId");

                    b.ToTable("VenueImage");

                    b.HasData(
                        new
                        {
                            VenueImageId = 1,
                            ImageUrl = "images/venues/pool_space_1.jpg",
                            VenueId = 3
                        },
                        new
                        {
                            VenueImageId = 2,
                            ImageUrl = "images/venues/pool_space_2.jpg",
                            VenueId = 3
                        },
                        new
                        {
                            VenueImageId = 3,
                            ImageUrl = "images/venues/universe_sports_1.jpg",
                            VenueId = 4
                        },
                        new
                        {
                            VenueImageId = 4,
                            ImageUrl = "images/venues/diamond_hub_1.jpg",
                            VenueId = 5
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("HealthIsWealth.Domain.Booking", b =>
                {
                    b.HasOne("HealthIsWealth.Domain.Timeslot", "Timeslot")
                        .WithMany()
                        .HasForeignKey("TimeslotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HealthIsWealth.Data.HealthIsWealthUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("Timeslot");

                    b.Navigation("User");
                });

            modelBuilder.Entity("HealthIsWealth.Domain.Facility", b =>
                {
                    b.HasOne("HealthIsWealth.Domain.Venue", "Venue")
                        .WithMany("Facilities")
                        .HasForeignKey("VenueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Venue");
                });

            modelBuilder.Entity("HealthIsWealth.Domain.FacilityImage", b =>
                {
                    b.HasOne("HealthIsWealth.Domain.Facility", "Facility")
                        .WithMany("FacilityImages")
                        .HasForeignKey("FacilityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Facility");
                });

            modelBuilder.Entity("HealthIsWealth.Domain.FacilitySport", b =>
                {
                    b.HasOne("HealthIsWealth.Domain.Facility", "Facility")
                        .WithMany("FacilitySports")
                        .HasForeignKey("FacilityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HealthIsWealth.Domain.Sport", "Sport")
                        .WithMany("FacilitySports")
                        .HasForeignKey("SportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Facility");

                    b.Navigation("Sport");
                });

            modelBuilder.Entity("HealthIsWealth.Domain.Review", b =>
                {
                    b.HasOne("HealthIsWealth.Domain.Booking", "Booking")
                        .WithMany()
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HealthIsWealth.Data.HealthIsWealthUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("Booking");

                    b.Navigation("User");
                });

            modelBuilder.Entity("HealthIsWealth.Domain.Timeslot", b =>
                {
                    b.HasOne("HealthIsWealth.Domain.Facility", "Facility")
                        .WithMany("Timeslots")
                        .HasForeignKey("FacilityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Facility");
                });

            modelBuilder.Entity("HealthIsWealth.Domain.VenueImage", b =>
                {
                    b.HasOne("HealthIsWealth.Domain.Venue", "Venue")
                        .WithMany("VenueImages")
                        .HasForeignKey("VenueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Venue");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("HealthIsWealth.Data.HealthIsWealthUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("HealthIsWealth.Data.HealthIsWealthUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HealthIsWealth.Data.HealthIsWealthUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("HealthIsWealth.Data.HealthIsWealthUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HealthIsWealth.Domain.Facility", b =>
                {
                    b.Navigation("FacilityImages");

                    b.Navigation("FacilitySports");

                    b.Navigation("Timeslots");
                });

            modelBuilder.Entity("HealthIsWealth.Domain.Sport", b =>
                {
                    b.Navigation("FacilitySports");
                });

            modelBuilder.Entity("HealthIsWealth.Domain.Venue", b =>
                {
                    b.Navigation("Facilities");

                    b.Navigation("VenueImages");
                });
#pragma warning restore 612, 618
        }
    }
}
